### ISSUE TITLE
data

### ISSUE THREAD

**Issue by linmoxiaomo** [m-hamza-mughal/Aerial-Template-Matching#1]
Hi, I want to know that did you train the network again using your own UAV datasets? and how do you label the train data? Or you test your data using the trained model in NCnet? Thanku

**Comment by m-hamza-mughal** [comment]
we'll be making our dataset public after acceptance of the publication and the paper has details regarding model and optimization.

**Comment by m-hamza-mughal** [comment]
Data has been open-sourced. Check README.md
